### ISSUE TITLE
Increased security

### ISSUE THREAD

**Issue by RobinHirst11** [KafetzisThomas/Pass-Hashing#1]
Look into SALT, an extra layer when it comes to hashing, it was developed by the CIA and is considered the best way to secure a password

**Comment by KafetzisThomas** [comment]
Nice idea, I've implemented salt for SHA hashes, while keeping bcrypt's existing salt mechanism intact. Additionally, I've added a verification check to ensure that messages match hashed values, including the salt: https://github.com/KafetzisThomas/Message-Hasher/commit/94be7d8fb5cb38b410c312a33411c6a261acafa1
